[build]
  command = "npm run build"
  publish = "build"
  environment = { VITE_WEB_SERVICE_URL = "https://backend-doodle.onrender.com" }

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  publish = "src"
  autoLaunch = true